In [2]:
import streamlit as st
import pandas as pd

#st.title("Hello Pycon IT")

df = pd.read_csv("./riders-info.csv")

In [3]:
df.head()

,Riders All Time in All Classes,Victories,2nd places,3rd places,Pole positions from '74 to 2022,Race fastest lap to 2022,World Championships
0,AGOSTINI Giacomo,122,35.0,2.0,9.0,117.0,15.0
1,ROSSI Valentino,115,67.0,53.0,65.0,96.0,9.0
2,NIETO Angel,90,35.0,14.0,34.0,81.0,13.0
3,MARQUEZ Marc,85,36.0,17.0,90.0,75.0,8.0
4,HAILWOOD Mike,76,25.0,11.0,NaN,79.0,9.0

In [8]:
df = pd.read_csv("./race-winners.csv")
df.head()

,Circuit,Class,Constructor,Country,Rider,Season
0,Circuit Of The Americas,Moto3™,KTM,ES,Jaume Masia,2022
1,Circuit Of The Americas,Moto2™,Kalex,IT,Tony Arbolino,2022
2,Circuit Of The Americas,MotoGP™,Ducati,IT,Enea Bastianini,2022
3,Termas de Río Hondo,Moto3™,GASGAS,ES,Sergio Garcia,2022
4,Termas de Río Hondo,MotoGP™,Aprilia,ES,Aleix Espargaro,2022

In [10]:
df[df['Class'] == "MotoGP™"]['Rider']

2         Enea Bastianini
4         Aleix Espargaro
6         Miguel Oliveira
11        Enea Bastianini
13      Francesco Bagnaia
              ...
3068        Leslie Graham
3071        William Doran
3073         Nello Pagani
3078        Leslie Graham
3080       Harold Daniell
Name: Rider, Length: 871, dtype: object